# Generated by Django 4.2.28 on 2026-02-24 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tp_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_width', models.FloatField(help_text='Adjacent road width in metres.')),
                ('building_height', models.FloatField(help_text='Proposed building height in metres.')),
                ('total_bua', models.FloatField(help_text='Total built-up area (all floors) in sq.ft.')),
                ('num_floors', models.IntegerField(help_text='Number of floors above ground.')),
                ('ground_coverage', models.FloatField(help_text='Ground floor footprint in sq.ft.')),
                ('has_basement', models.BooleanField(default=False)),
                ('is_sprinklered', models.BooleanField(default=False)),
                ('has_lift', models.BooleanField(blank=True, help_text='None = not declared; True = provided; False = not provided.', null=True)),
                ('side_margin', models.FloatField(blank=True, help_text='Minimum proposed side margin in metres.', null=True)),
                ('rear_margin', models.FloatField(blank=True, help_text='Minimum proposed rear margin in metres.', null=True)),
                ('stair_width', models.FloatField(blank=True, help_text='Staircase clear width in metres.', null=True)),
                ('tread_mm', models.FloatField(blank=True, help_text='Staircase tread depth in mm.', null=True)),
                ('riser_mm', models.FloatField(blank=True, help_text='Staircase riser height in mm.', null=True)),
                ('stair_headroom', models.FloatField(blank=True, help_text='Headroom on staircase in metres.', null=True)),
                ('window_area', models.FloatField(blank=True, help_text='Total window area of habitable room in sq.m.', null=True)),
                ('floor_area', models.FloatField(blank=True, help_text='Floor area of habitable room in sq.m.', null=True)),
                ('room_height', models.FloatField(blank=True, help_text='Floor-to-ceiling height (habitable) in metres.', null=True)),
                ('bathroom_height', models.FloatField(blank=True, help_text='Floor-to-ceiling height (bathroom) in metres.', null=True)),
                ('basement_height', models.FloatField(blank=True, help_text='Basement clear height in metres.', null=True)),
                ('wall_height_road_side', models.FloatField(blank=True, help_text='Road-side boundary wall height in metres.', null=True)),
                ('wall_height_other_side', models.FloatField(blank=True, help_text='Non-road boundary wall height in metres.', null=True)),
                ('num_exits', models.IntegerField(blank=True, null=True)),
                ('corridor_width', models.FloatField(blank=True, help_text='m', null=True)),
                ('door_width', models.FloatField(blank=True, help_text='m', null=True)),
                ('travel_distance', models.FloatField(blank=True, help_text='m', null=True)),
                ('fire_separation_distance', models.FloatField(blank=True, help_text='m', null=True)),
                ('fire_door_rating', models.FloatField(blank=True, help_text='minutes', null=True)),
                ('has_fire_lift', models.BooleanField(blank=True, null=True)),
                ('has_firefighting_shaft', models.BooleanField(blank=True, null=True)),
                ('refuge_area_pct', models.FloatField(blank=True, help_text='Refuge area as % of floor area.', null=True)),
                ('distance_to_wide_road', models.FloatField(blank=True, help_text='Distance in metres to nearest 36 m or 45 m road (for incentive FSI check).', null=True)),
                ('notes', models.TextField(blank=True, help_text='Free-form notes from architect.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='tp_ingestion.plot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=100)),
                ('rule_source', models.CharField(help_text='"GDCR" or "NBC"', max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('INFO', 'Info / Declaration required'), ('NA', 'Not applicable'), ('MISSING_DATA', 'Missing data')], max_length=20)),
                ('required_value', models.FloatField(blank=True, null=True)),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_results', to='rules_engine.buildingproposal')),
            ],
            options={
                'ordering': ['rule_source', 'category', 'rule_id'],
                'unique_together': {('proposal', 'rule_id')},
            },
        ),
    ]
