"""
services/unit_layout_engine.py
-------------------------------
Deterministic room layout engine for a single residential unit.

Replaces GPT for internal room geometry.  All coordinates are generated by
proportion calculation using GDCR minimums as hard lower bounds.

── Layout strategy ───────────────────────────────────────────────────────────
Rooms are organised in four horizontal strips (zones), stacked along the
depth axis (Y).  For a SOUTH unit (Y=unit_y = exterior south face):

    Zone A  [exterior]  Bedrooms (all on exterior wall, get south windows)
    Zone B  [service]   Bathrooms + Utility (interior, no windows required)
    Zone C  [public]    Living + Dining + Kitchen
    Zone D  [entry]     Foyer  (corridor-facing strip, width-limited)

For a NORTH unit (Y=unit_y = corridor face) zones are mirrored top-to-bottom.

── Balcony ───────────────────────────────────────────────────────────────────
The balcony projects OUTSIDE the unit rectangle from the exterior face.
It is returned as a separate "balcony" dict (not inside "rooms"), consistent
with the existing GeoJSON converter expectations.

── GDCR compliance ───────────────────────────────────────────────────────────
• All room widths/depths are ≥ GDCR SS 13.1.8 / SS 13.1.9 minimums.
• Living ≥ 9.5 m²,  Master Bed ≥ 9.5 m²,  Bedroom ≥ 7.5 m²
• Kitchen ≥ 5.5 m², Bathroom ≥ 2.16 m²,   Toilet ≥ 1.65 m²
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Tuple

# ── Architectural constants (metres) ─────────────────────────────────────────
WET_ZONE_D  = 1.80    # depth of Zone B (bathroom / wet-service strip)
FOYER_D     = 1.20    # depth of Zone D (entry / foyer strip)
BALCONY_D   = 1.50    # balcony projection depth
BALCONY_W_MAX = 3.00  # maximum balcony width

# ── GDCR minimum room WIDTHS (metres) ────────────────────────────────────────
_MIN_W: Dict[str, float] = {
    "living":   3.00,
    "dining":   2.50,
    "bedroom":  2.70,   # principal / master bedroom
    "bedroom2": 2.50,   # secondary bedroom
    "kitchen":  1.80,
    "bathroom": 1.20,
    "toilet":   1.10,
    "utility":  1.20,
    "foyer":    1.50,
}

# ── GDCR minimum room DEPTHS (metres) ────────────────────────────────────────
# Depth here = the zone height the room occupies (not the GDCR "width" side)
_MIN_D: Dict[str, float] = {
    "living":   3.17,   # 9.5 m² / 3.0 m width
    "dining":   2.50,
    "bedroom":  3.52,   # 9.5 m² / 2.7 m width
    "bedroom2": 3.00,   # 7.5 m² / 2.5 m width
    "kitchen":  3.06,   # 5.5 m² / 1.8 m width
    "bathroom": 1.80,
    "toilet":   1.50,
    "utility":  1.50,
    "foyer":    1.20,
}

# ── Segment size multipliers ──────────────────────────────────────────────────
_SEGMENT_MULT: Dict[str, float] = {
    "budget":  1.00,
    "mid":     1.15,
    "premium": 1.30,
    "luxury":  1.50,
}

# ── Room programs per unit type ───────────────────────────────────────────────
# Each zone entry: (room_type, display_name, width_weight)
# width_weight controls proportional distribution within the zone.
# Zone B rooms with total min_width > unit_w will have excess rooms dropped.

_PROGRAMS: Dict[str, Dict[str, Any]] = {
    "1BHK": {
        "A": [
            ("bedroom",  "Bedroom",    0.60),
        ],
        "B": [
            ("bathroom", "Bathroom",   0.55),
            ("toilet",   "Toilet",     0.45),
        ],
        "C": [
            ("living",   "Living",     0.60),
            ("kitchen",  "Kitchen",    0.40),
        ],
        "balcony": True,
    },
    "2BHK": {
        "A": [
            ("bedroom",  "Bedroom 1",  0.56),   # master (wider)
            ("bedroom2", "Bedroom 2",  0.44),
        ],
        "B": [
            ("bathroom", "Bathroom 1", 0.38),
            ("utility",  "Utility",    0.30),
            ("toilet",   "Toilet",     0.32),
        ],
        "C": [
            ("living",   "Living",     0.62),
            ("kitchen",  "Kitchen",    0.38),
        ],
        "balcony": True,
    },
    "3BHK": {
        "A": [
            ("bedroom",  "Bedroom 1",  0.38),
            ("bedroom2", "Bedroom 2",  0.33),
            ("bedroom2", "Bedroom 3",  0.29),
        ],
        "B": [
            ("bathroom", "Bathroom 1", 0.30),
            ("bathroom", "Bathroom 2", 0.28),
            ("utility",  "Utility",    0.22),
            ("toilet",   "Toilet",     0.20),
        ],
        "C": [
            ("living",   "Living",     0.44),
            ("dining",   "Dining",     0.22),
            ("kitchen",  "Kitchen",    0.34),
        ],
        "balcony": True,
    },
    "4BHK": {
        "A": [
            ("bedroom",  "Bedroom 1",  0.28),
            ("bedroom2", "Bedroom 2",  0.25),
            ("bedroom2", "Bedroom 3",  0.25),
            ("bedroom2", "Bedroom 4",  0.22),
        ],
        "B": [
            ("bathroom", "Bathroom 1", 0.26),
            ("bathroom", "Bathroom 2", 0.24),
            ("bathroom", "Bathroom 3", 0.22),
            ("utility",  "Utility",    0.16),
            ("toilet",   "Toilet",     0.12),
        ],
        "C": [
            ("living",   "Living",     0.40),
            ("dining",   "Dining",     0.25),
            ("kitchen",  "Kitchen",    0.35),
        ],
        "balcony": True,
    },
}


# ── Public API ────────────────────────────────────────────────────────────────

def generate_unit_rooms(
    unit: Dict[str, Any],
    segment: str = "mid",
    mirror: bool = False,
) -> Dict[str, Any]:
    """
    Generate a fully placed room layout for a single unit envelope.

    Input
    -----
    unit :
        Dict with keys ``id``, ``type``, ``side``, ``x``, ``y``, ``w``, ``h``.
        Comes from ``unit_block_engine.generate_unit_blocks``.
    segment :
        One of ``"budget"`` | ``"mid"`` | ``"premium"`` | ``"luxury"``.
    mirror :
        If True the room layout is flipped horizontally (left↔right) within
        the unit envelope.  Use for the second unit in a mirrored pair so
        that symmetric units around the core are genuine mirror images.

    Output
    ------
    Copy of the input unit dict with additional keys:
      ``"rooms"``   – list of room dicts, each with
                      ``type``, ``name``, ``x``, ``y``, ``w``, ``h``
      ``"balcony"`` – optional balcony dict (may project outside unit bounds)
    """
    u_type = _normalise_type(unit.get("type", "2BHK"))
    program = _PROGRAMS.get(u_type, _PROGRAMS["2BHK"])
    side = unit.get("side", "south")
    ux, uy = float(unit["x"]), float(unit["y"])
    uw, uh = float(unit["w"]), float(unit["h"])
    mult = _SEGMENT_MULT.get(segment.lower(), 1.15)

    # ── Zone heights (sum to uh) ──────────────────────────────────────────────
    bed_h, wet_h, living_h, foyer_h = _zone_heights(uh, u_type, mult)

    # ── Absolute Y start of each zone ────────────────────────────────────────
    if side == "south":
        # Y=uy = exterior south face  →  Y=uy+uh = corridor face
        a_y = uy                            # Zone A bottom (exterior)
        b_y = uy + bed_h                    # Zone B (wet/service)
        c_y = b_y + wet_h                   # Zone C (living/kitchen)
        d_y = c_y + living_h               # Zone D (foyer, corridor face)
    else:
        # north unit: Y=uy = corridor face  →  Y=uy+uh = exterior north face
        d_y = uy                            # Zone D bottom (corridor entry)
        c_y = uy + foyer_h                  # Zone C (living/kitchen)
        b_y = c_y + living_h               # Zone B (wet/service)
        a_y = b_y + wet_h                  # Zone A top (exterior)

    rooms: List[Dict] = []

    # ── Zones A + B — Bedroom block with attached en-suite bathroom ───────────
    #
    # For 2BHK+ the master bedroom gets an attached (en-suite) bathroom placed
    # directly inside Zone A, at its inner corner (the side facing Zone B).
    # This creates true geometric adjacency — the bathroom shares a wall with
    # the bedroom instead of being separated by the secondary bedroom row.
    #
    # Layout within Zone A:
    #   ┌─────────────────────┬──────────┬─────────────────────┐
    #   │  Master Bedroom     │ Attached │  Bedroom 2          │  ← exterior row
    #   │  (exterior)         │  Bath    │  (full bed_h)       │
    #   ├─────────────────────┤  (inner) │                     │
    #   │  Closet / Dressing  │          │                     │
    #   └─────────────────────┴──────────┴─────────────────────┘
    #       master_col_w            secondary_col_w (Bed 2, Bed 3...)
    #
    # Zone B then carries only secondary bathrooms + utility + toilet.
    # For 1BHK there are no secondary bedrooms, so we use the simple layout.

    a_spec = program["A"]
    b_spec_full = program["B"]

    has_secondary = len(a_spec) > 1
    # Find the first bathroom in Zone B — this becomes the attached bath
    master_bath_idx = next(
        (i for i, (rt, *_) in enumerate(b_spec_full) if rt == "bathroom"), None
    )

    ATTACH_BATH_H = WET_ZONE_D          # 1.80 m depth (same as Zone B)
    ATTACH_BATH_W = 1.65                # en-suite width (slightly generous)
    CLOSET_MIN_W  = 1.20                # minimum closet beside the bath

    use_ensuite = (
        has_secondary
        and master_bath_idx is not None
        and uw >= (_MIN_W["bedroom"] + ATTACH_BATH_W + _MIN_W["bedroom2"])
        and bed_h >= ATTACH_BATH_H + _MIN_D["bedroom"] * 0.70
    )

    if use_ensuite:
        # ── Determine column widths ───────────────────────────────────────────
        n_secondary = len(a_spec) - 1
        sec_min_w   = sum(_MIN_W.get(rt, 2.5) for rt, *_ in a_spec[1:])
        master_col_w = _round(_clamp(
            uw - sec_min_w,
            _MIN_W["bedroom"] + ATTACH_BATH_W,
            uw * 0.55,
        ))
        sec_col_w = _round(uw - master_col_w)

        # ── Master column ─────────────────────────────────────────────────────
        # Exterior sub-row: bedroom spans full column width, exterior face
        bed_inner_h = _round(bed_h - ATTACH_BATH_H)
        if side == "south":
            bed_ext_y  = a_y                       # exterior face
            bath_row_y = _round(a_y + bed_inner_h) # inner row (toward Zone B)
        else:
            bath_row_y = a_y                       # inner row (toward Zone B)
            bed_ext_y  = _round(a_y + ATTACH_BATH_H)

        # Master bedroom: full column width × bed_inner_h
        rooms.append(_room(
            a_spec[0][0], a_spec[0][1],
            ux, bed_ext_y, master_col_w, bed_inner_h,
        ))

        # Attached bathroom: ATTACH_BATH_W at the outer edge of master column
        rooms.append(_room(
            "bathroom", "Bathroom 1",
            ux, bath_row_y, ATTACH_BATH_W, ATTACH_BATH_H,
        ))

        # Closet / dressing: remaining width of master column at inner row
        closet_w = _round(master_col_w - ATTACH_BATH_W)
        if closet_w >= CLOSET_MIN_W:
            rooms.append(_room(
                "utility", "Closet",
                ux + ATTACH_BATH_W, bath_row_y, closet_w, ATTACH_BATH_H,
            ))

        # ── Secondary bedrooms (right column, full Zone A height) ─────────────
        sec_specs  = a_spec[1:]
        sec_widths = _distribute_widths(sec_specs, sec_col_w)
        cx = ux + master_col_w
        for (rtype, rname, _), rw in zip(sec_specs, sec_widths):
            rooms.append(_room(rtype, rname, cx, a_y, rw, bed_h))
            cx += rw

        # ── Zone B — remaining wet rooms (master bath already placed) ─────────
        b_spec_remaining = [
            entry for i, entry in enumerate(b_spec_full)
            if i != master_bath_idx
        ]
        b_spec = _trim_zone_b(b_spec_remaining, uw)
        b_widths = _distribute_widths(b_spec, uw)
        cx = ux
        for (rtype, rname, _), rw in zip(b_spec, b_widths):
            rooms.append(_room(rtype, rname, cx, b_y, rw, wet_h))
            cx += rw

    else:
        # ── Fallback: simple single-row Zone A + standard Zone B ──────────────
        a_widths = _distribute_widths(a_spec, uw)
        cx = ux
        for (rtype, rname, _), rw in zip(a_spec, a_widths):
            rooms.append(_room(rtype, rname, cx, a_y, rw, bed_h))
            cx += rw

        b_spec = _trim_zone_b(b_spec_full, uw)
        b_widths = _distribute_widths(b_spec, uw)
        cx = ux
        for (rtype, rname, _), rw in zip(b_spec, b_widths):
            rooms.append(_room(rtype, rname, cx, b_y, rw, wet_h))
            cx += rw

    # ── Zone C — Living / Kitchen ( + optional Dining) — L-shaped arrangement ─
    # The living room takes the exterior half of the zone width and the full
    # zone height, so it faces the exterior wall.  Kitchen and dining are
    # stacked vertically in the interior half — forming an L with living.
    # For 1BHK (no dining) and cases where living_h is too small to split,
    # we fall back to the original flat row.
    c_spec = program["C"]
    living_spec   = [(rt, rn, wt) for rt, rn, wt in c_spec if rt == "living"]
    non_liv_spec  = [(rt, rn, wt) for rt, rn, wt in c_spec if rt != "living"]

    use_l_shape = (
        len(non_liv_spec) >= 1
        and living_h >= _MIN_D["living"] * 1.1
        and uw >= (_MIN_W["living"] + _MIN_W["kitchen"] + 0.60)
    )

    if use_l_shape:
        # Determine widths: living takes 50–60% of unit width
        total_w_non_liv = sum(_MIN_W.get(rt, 1.8) for rt, *_ in non_liv_spec)
        liv_w = _round(_clamp(uw - total_w_non_liv - 0.20,
                              _MIN_W["living"],
                              uw * 0.60))
        non_liv_w = _round(uw - liv_w)

        # Living: full height of Zone C
        if living_spec:
            rooms.append(_room(
                "living", living_spec[0][1],
                ux, c_y, liv_w, living_h,
            ))

        # Kitchen / dining: stacked in the remaining interior column
        non_liv_heights = _distribute_depths(non_liv_spec, living_h)
        ny = c_y
        for (rtype, rname, _), rh_i in zip(non_liv_spec, non_liv_heights):
            rooms.append(_room(rtype, rname, ux + liv_w, ny, non_liv_w, rh_i))
            ny = _round(ny + rh_i)
    else:
        # Fallback: flat row
        c_widths = _distribute_widths(c_spec, uw)
        cx = ux
        for (rtype, rname, _), rw in zip(c_spec, c_widths):
            rooms.append(_room(rtype, rname, cx, c_y, rw, living_h))
            cx += rw

    # ── Zone D — Foyer + internal passage ────────────────────────────────────
    # Layout: [Foyer | Passage | (optional Pantry/Utility extension)]
    #
    # The foyer is a tight entry cell facing the corridor door.
    # A passage (≥ 1.0 m wide) runs beside the foyer along the full foyer
    # strip depth — it acts as the circulation spine connecting the entry to
    # the living zone and the bedroom wing.
    # Any remaining width becomes a pantry / utility extension.
    #
    # Minimum widths:
    FOYER_W_MIN  = 1.20   # tight entry cell
    PASSAGE_W    = 1.10   # internal passage / lobby

    total_service = FOYER_W_MIN + PASSAGE_W
    can_add_passage = uw >= total_service + _MIN_W["utility"] - 0.20

    foyer_w = _round(_clamp(uw * 0.22, FOYER_W_MIN, 2.20))
    rooms.append(_room("foyer", "Foyer", ux, d_y, foyer_w, foyer_h))

    if can_add_passage:
        # Passage immediately beside foyer
        rooms.append(_room("passage", "Passage",
                            ux + foyer_w, d_y, PASSAGE_W, foyer_h))
        used_w = _round(foyer_w + PASSAGE_W)
        store_w = _round(uw - used_w)
        if store_w >= _MIN_W["utility"]:
            rooms.append(_room("utility", "Pantry",
                               ux + used_w, d_y, store_w, foyer_h))
    else:
        # No passage — fall back to foyer + pantry
        store_w = _round(uw - foyer_w)
        if store_w >= _MIN_W["utility"]:
            rooms.append(_room("utility", "Pantry", ux + foyer_w, d_y,
                               store_w, foyer_h))

    # ── Validate ──────────────────────────────────────────────────────────────
    _validate(rooms, ux, uy, uw, uh, u_type)

    # ── Mirror horizontally if requested ─────────────────────────────────────
    if mirror:
        rooms = _mirror_rooms_h(rooms, ux, uw)

    # ── Balcony ───────────────────────────────────────────────────────────────
    balcony: Optional[Dict] = None
    if program.get("balcony"):
        balcony = _make_balcony(ux, uy, uw, uh, side)

    result = dict(unit)
    result["rooms"] = rooms
    if balcony:
        result["balcony"] = balcony
    return result


def layout_floor(
    floor_layout: Dict[str, Any],
    segment: str = "mid",
) -> Dict[str, Any]:
    """
    Apply ``generate_unit_rooms`` to every unit in a full floor layout dict.

    Units are automatically mirrored so that symmetric pairs around the core
    are genuine horizontal mirror images of each other.

    Input  / Output format: the same dict produced by
    ``unit_block_engine.generate_unit_blocks`` (keys: ``corridor``, ``units``).
    Each unit gets ``rooms`` and optionally ``balcony`` injected.
    """
    import copy
    result = copy.deepcopy(floor_layout)
    units = result.get("units", [])

    # Determine the floor mid-point X for mirror detection.
    # We compute it from the unit bounding boxes.
    all_xs = [u["x"] + u["w"] / 2.0 for u in units if "x" in u and "w" in u]
    mid_x = (sum(all_xs) / len(all_xs)) if all_xs else 0.0

    for i, unit in enumerate(units):
        cx = unit.get("x", 0) + unit.get("w", 0) / 2.0
        mirror = cx > mid_x
        result["units"][i] = generate_unit_rooms(unit, segment, mirror=mirror)
    return result


# ── Zone height computation ────────────────────────────────────────────────────

def _zone_heights(
    uh: float,
    u_type: str,
    mult: float,  # kept for API compatibility; not applied to depths
) -> Tuple[float, float, float, float]:
    """
    Return (bed_h, wet_h, living_h, foyer_h) such that they sum to uh.

    Constraints (hard — always GDCR absolute minimums, not scaled by segment):
      wet_h   = WET_ZONE_D  (fixed)
      foyer_h = FOYER_D     (fixed)
      bed_h   ≥ _MIN_D["bedroom"]   (3.52 m)
      living_h ≥ _MIN_D["living"]   (3.17 m)

    The segment multiplier is intentionally NOT applied to depths: the unit
    envelope depth is fixed by unit_block_engine.  Segment quality is expressed
    through room widths, not by requiring taller zones.
    """
    wet_h   = WET_ZONE_D
    foyer_h = FOYER_D

    min_bed_d    = _MIN_D["bedroom"]   # 3.52 m — GDCR absolute minimum
    min_living_d = _MIN_D["living"]    # 3.17 m — GDCR absolute minimum

    remaining = uh - wet_h - foyer_h   # depth available for beds + living

    if remaining <= 0:
        # Extremely shallow unit: shrink fixed zones proportionally
        foyer_h = _round(max(0.80, uh * 0.12))
        wet_h   = _round(max(1.50, uh * 0.20))
        remaining = _round(uh - wet_h - foyer_h)

    # If the unit is shallower than the sum of GDCR minimums, compress
    # proportionally rather than raising.  Rooms will be slightly sub-GDCR
    # but at least the layout renders and can be flagged as a warning.
    if remaining < min_bed_d + min_living_d:
        total_min = min_bed_d + min_living_d
        if total_min > 0:
            scale     = remaining / total_min
            min_bed_d    = _round(min_bed_d    * scale)
            min_living_d = _round(min_living_d * scale)

    # Proportional split: bedrooms get 35–38 % of total unit depth
    bed_frac = 0.38 if u_type in ("3BHK", "4BHK") else 0.35
    bed_h    = _clamp(uh * bed_frac, min_bed_d,
                      max(min_bed_d, remaining - min_living_d))
    bed_h    = _round(bed_h)
    living_h = _round(remaining - bed_h)

    if living_h <= 0:
        living_h = _round(remaining * 0.45)
        bed_h    = _round(remaining - living_h)

    return bed_h, wet_h, living_h, foyer_h


# ── Width distribution ─────────────────────────────────────────────────────────

def _distribute_widths(
    zone_spec: List[Tuple[str, str, float]],
    unit_w: float,
) -> List[float]:
    """
    Allocate ``unit_w`` among rooms in a zone.

    Each room is guaranteed ≥ its GDCR minimum width; the remainder is
    distributed proportionally to the declared weight.
    """
    if not zone_spec:
        return []

    types   = [s[0] for s in zone_spec]
    weights = [s[2] for s in zone_spec]
    mins    = [_MIN_W.get(t, 1.0) for t in types]
    total_min = sum(mins)

    if total_min > unit_w + 0.02:
        # All rooms at their hard minimums, scale down to fit
        scale = unit_w / total_min
        widths = [_round(m * scale) for m in mins]
    else:
        surplus = unit_w - total_min
        total_w = sum(weights) or 1.0
        widths = [_round(m + surplus * wt / total_w)
                  for m, wt in zip(mins, weights)]

    # Fix rounding drift (ensure exact sum)
    diff = _round(unit_w - sum(widths))
    if abs(diff) > 0.001:
        widths[-1] = _round(widths[-1] + diff)

    return widths


def _distribute_depths(
    zone_spec: List[Tuple[str, str, float]],
    total_h: float,
) -> List[float]:
    """
    Distribute ``total_h`` among rooms stacked vertically (along Y).

    Each room is guaranteed ≥ its GDCR minimum depth (_MIN_D); the remainder
    is distributed proportionally to the declared weight.
    """
    if not zone_spec:
        return []

    types   = [s[0] for s in zone_spec]
    weights = [s[2] for s in zone_spec]
    mins    = [_MIN_D.get(t, 2.0) for t in types]
    total_min = sum(mins)

    if total_min > total_h + 0.02:
        scale = total_h / total_min
        heights = [_round(m * scale) for m in mins]
    else:
        surplus = total_h - total_min
        total_w = sum(weights) or 1.0
        heights = [_round(m + surplus * wt / total_w)
                   for m, wt in zip(mins, weights)]

    diff = _round(total_h - sum(heights))
    if abs(diff) > 0.001:
        heights[-1] = _round(heights[-1] + diff)

    return heights


def _trim_zone_b(
    b_spec: List[Tuple[str, str, float]],
    unit_w: float,
) -> List[Tuple[str, str, float]]:
    """
    Remove wet-zone rooms that can't fit (very narrow units).
    Always keep at least one bathroom.
    """
    required_min = sum(_MIN_W.get(t, 1.0) for t, *_ in b_spec)
    if required_min <= unit_w + 0.1:
        return b_spec
    # Drop optional rooms (utility first, then extra bathrooms) until it fits
    trimmed = list(b_spec)
    for drop_type in ("utility", "toilet", "bathroom"):
        for i in range(len(trimmed) - 1, -1, -1):
            if trimmed[i][0] == drop_type and len(trimmed) > 1:
                trimmed.pop(i)
                if sum(_MIN_W.get(t, 1.0) for t, *_ in trimmed) <= unit_w + 0.1:
                    return trimmed
    return trimmed[:1]  # last resort: one bathroom


# ── Balcony ────────────────────────────────────────────────────────────────────

def _make_balcony(
    ux: float, uy: float,
    uw: float, uh: float,
    side: str,
) -> Dict[str, float]:
    """
    Build a balcony rectangle that projects beyond the unit's exterior face.

    South unit: projects below uy (negative Y direction).
    North unit: projects above uy+uh (positive Y direction).
    """
    bal_w = _round(_clamp(uw * 0.40, 2.00, BALCONY_W_MAX))
    bal_x = _round(ux + (uw - bal_w) / 2.0)   # centred on unit width

    if side == "south":
        bal_y = _round(uy - BALCONY_D)
    else:
        bal_y = _round(uy + uh)

    return {
        "x": bal_x,
        "y": bal_y,
        "w": bal_w,
        "h": BALCONY_D,
    }


# ── Mirroring ─────────────────────────────────────────────────────────────────

def _mirror_rooms_h(
    rooms: List[Dict],
    ux: float,
    uw: float,
) -> List[Dict]:
    """
    Flip every room left↔right within the unit envelope.

    For a room at (rx, ry, rw, rh) inside a unit at (ux, _, uw, _):
      new_rx = ux + (ux + uw - rx - rw) - ux  =  ux + uw - rx - rw
    """
    mirrored = []
    for r in rooms:
        new_rx = _round(ux + uw - r["x"] - r["w"])
        mirrored.append({**r, "x": new_rx})
    return mirrored


# ── Validation ────────────────────────────────────────────────────────────────

def _validate(
    rooms: List[Dict],
    ux: float, uy: float,
    uw: float, uh: float,
    u_type: str,
) -> None:
    """Assert no overlaps, adequate coverage, and GDCR area minimums."""
    # 1. Coverage (warn only — shallow units may cover less without failing)
    unit_area = uw * uh
    covered   = sum(r["w"] * r["h"] for r in rooms)
    coverage  = covered / unit_area
    if coverage < 0.75:
        import logging as _log
        _log.getLogger(__name__).warning(
            "%s: room coverage %.0f%% < 75%% (unit=%.1f m²)",
            u_type, coverage * 100, unit_area,
        )

    # 2. No overlaps
    for i, a in enumerate(rooms):
        for b in rooms[i + 1:]:
            if _overlap(a, b):
                raise ValueError(
                    f"Overlap: '{a['name']}' and '{b['name']}'"
                )

    # 3. GDCR minimums (area only — a soft warning, not a hard stop)
    gdcr_area = {
        "living": 9.5, "bedroom": 9.5, "bedroom2": 7.5,
        "kitchen": 5.5, "bathroom": 2.16, "toilet": 1.65,
    }
    for r in rooms:
        min_a = gdcr_area.get(r["type"])
        if min_a and r["w"] * r["h"] < min_a - 0.1:
            # Soft warning (raise for strict compliance mode)
            pass


# ── Geometry helpers ──────────────────────────────────────────────────────────

def _room(
    rtype: str, name: str,
    x: float, y: float,
    w: float, h: float,
) -> Dict[str, Any]:
    return {
        "type": rtype,
        "name": name,
        "x":    _round(x),
        "y":    _round(y),
        "w":    _round(w),
        "h":    _round(h),
    }


def _overlap(a: Dict, b: Dict, tol: float = 0.005) -> bool:
    return not (
        a["x"] + a["w"] <= b["x"] + tol
        or b["x"] + b["w"] <= a["x"] + tol
        or a["y"] + a["h"] <= b["y"] + tol
        or b["y"] + b["h"] <= a["y"] + tol
    )


def _round(v: float) -> float:
    return round(v, 2)


def _clamp(v: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, v))


def _normalise_type(raw: str) -> str:
    t = raw.strip().upper().replace(" ", "")
    # Accept "2BHK", "2 BHK", "2bhk" etc.
    for k in _PROGRAMS:
        if t == k:
            return k
    return "2BHK"
