# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tp_ingestion", "0002_add_plot_road_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="designation",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
