# Generated by Django 4.2.28 on 2026-03-20 02:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_ingestion', '0004_add_block_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('tp_scheme', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=0)),
                ('centerline', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=0)),
                ('width_m', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='blocklabel',
            new_name='tp_ingestio_text_3e1360_idx',
            old_name='tp_ingestion_blocklabel_text_9f2f3a_idx',
        ),
        migrations.RenameIndex(
            model_name='blocklabel',
            new_name='tp_ingestio_plot_id_eaa209_idx',
            old_name='tp_ingestion_blocklabel_plot_t_4b6b0b_idx',
        ),
        migrations.AddField(
            model_name='plot',
            name='label_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=0),
        ),
        migrations.AddIndex(
            model_name='road',
            index=models.Index(fields=['city', 'tp_scheme'], name='tp_ingestio_city_0eb2f2_idx'),
        ),
    ]
