"use client";

import { motion, AnimatePresence } from "framer-motion";

interface TermsModalProps {
  isOpen: boolean;
  onClose: () => void;
  onAgree?: () => void;
}

export default function TermsModal({ isOpen, onClose, onAgree }: TermsModalProps) {
  const handleAgree = () => {
    if (onAgree) onAgree();
    onClose();
  };
  return (
    <AnimatePresence>
      {isOpen && (
        <div className="terms-modal-overlay">
          <motion.div 
            className="terms-modal-backdrop"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
          />
          <motion.div 
            className="terms-modal-content"
            initial={{ opacity: 0, scale: 0.95, y: 30 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 30 }}
            transition={{ 
              type: "spring", 
              damping: 25, 
              stiffness: 300,
              mass: 0.8
            }}
          >
            <div className="terms-modal-header">
              <h2>Terms & Conditions</h2>
              <button 
                type="button" 
                className="terms-close-btn" 
                onClick={onClose}
                aria-label="Close modal"
              >
                &times;
              </button>
            </div>
            
            <div className="terms-modal-body">
              <section>
                <h3>1. Introduction</h3>
                <p>Welcome to AI Architect. By accessing or using our platform, you agree to be bound by these Terms and Conditions. Our platform provides AI-driven architectural design assistance and project management tools.</p>
              </section>

              <section>
                <h3>2. Intellectual Property</h3>
                <p>All AI-generated designs, models, and outputs created through the platform are subject to the licensing terms of your specific subscription. AI Architect retains ownership of the underlying algorithms and proprietary data used to generate these outputs.</p>
              </section>

              <section>
                <h3>3. User Responsibilities</h3>
                <p>As a user, you are responsible for the accuracy of the data you provide to the AI. Architectural outputs generated by our AI should be reviewed by licensed professionals before implementation in real-world construction projects.</p>
              </section>

              <section>
                <h3>4. Privacy & Data Security</h3>
                <p>Your privacy is paramount. We use industry-standard encryption to protect your project data. By using the service, you consent to our collection and use of data as outlined in our Privacy Policy.</p>
              </section>

              <section>
                <h3>5. Limitation of Liability</h3>
                <p>AI Architect is provided "as is." We are not liable for any structural failures, financial losses, or legal disputes arising from the use of AI-generated designs without professional human verification.</p>
              </section>

              <section>
                <h3>6. Account Termination</h3>
                <p>We reserve the right to suspend or terminate accounts that violate our usage policies or engage in unauthorized scraping of our AI models.</p>
              </section>

              <div className="terms-modal-footer-info">
                Last Updated: March 2026
              </div>
            </div>

            <div className="terms-modal-actions">
              <button 
                type="button" 
                className="auth-btn-primary" 
                onClick={handleAgree}
                style={{ width: '100%', margin: 0 }}
              >
                I AGREE & UNDERSTAND
              </button>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}
