# Generated by Django 4.2.28 on 2026-02-24 13:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envelope_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('VALID', 'Valid — all towers placed with spacing satisfied'), ('TOO_TIGHT', 'Too tight — fewer towers placed or spacing fail'), ('NO_FIT', 'No fit — not even one tower can fit'), ('INVALID_INPUT', 'Invalid input — bad parameters'), ('ERROR', 'Unexpected error during computation')], max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Populated when status is ERROR.')),
                ('n_towers_requested', models.IntegerField()),
                ('n_towers_placed', models.IntegerField()),
                ('building_height_m', models.FloatField()),
                ('spacing_required_m', models.FloatField(help_text='max(H/3, minimum_spacing_m) in metres.')),
                ('spacing_required_dxf', models.FloatField(help_text='spacing_required_m converted to DXF feet.')),
                ('orientation_primary_deg', models.FloatField(blank=True, help_text='Primary orientation angle (degrees) from MBR longest edge.', null=True)),
                ('orientation_secondary_deg', models.FloatField(blank=True, help_text='Secondary orientation angle = primary + 90°.', null=True)),
                ('packing_mode', models.CharField(blank=True, choices=[('ROW_WISE', 'Row-wise — along principal axis'), ('COL_WISE', 'Col-wise — across principal axis (perpendicular)')], help_text='Which packing strategy won: ROW_WISE or COL_WISE.', max_length=10, null=True)),
                ('grid_resolution_dxf', models.FloatField(blank=True, help_text='Adaptive grid resolution (DXF feet) used for the first tower.', null=True)),
                ('placement_audit', models.JSONField(default=list, help_text='List of spacing check dicts, one per tower pair: {pair, gap_dxf, gap_m, required_m, status, gdcr_clause, formula}')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='envelope_engine.plotenvelope')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='FootprintRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower_index', models.IntegerField(help_text='0-based placement sequence index.')),
                ('footprint_geom', django.contrib.gis.db.models.fields.PolygonField(help_text='Placed building footprint rectangle (DXF feet, SRID=0).', srid=0)),
                ('footprint_area_sqft', models.FloatField()),
                ('footprint_width_dxf', models.FloatField(help_text='Width along orientation angle (DXF feet).')),
                ('footprint_depth_dxf', models.FloatField(help_text='Depth perpendicular to orientation (DXF feet).')),
                ('footprint_width_m', models.FloatField()),
                ('footprint_depth_m', models.FloatField()),
                ('orientation_angle_deg', models.FloatField(help_text='Angle used for grid rotation (degrees from x-axis).')),
                ('orientation_label', models.CharField(choices=[('PRIMARY', 'Primary — along MBR longer edge'), ('PERPENDICULAR', 'Perpendicular — across MBR'), ('FORCED', 'Forced — override angle (COL_WISE mode)')], help_text='PRIMARY | PERPENDICULAR | FORCED', max_length=15)),
                ('source_component_index', models.IntegerField(default=0, help_text='Which MultiPolygon component this footprint was found in (0-based).')),
                ('grid_resolution_dxf', models.FloatField(help_text='Adaptive grid resolution used for this footprint (DXF feet).')),
                ('min_spacing_to_adjacent_dxf', models.FloatField(blank=True, help_text='Minimum gap to any other placed tower (DXF feet).', null=True)),
                ('min_spacing_to_adjacent_m', models.FloatField(blank=True, help_text='Minimum gap to any other placed tower (metres).', null=True)),
                ('spacing_status', models.CharField(choices=[('PASS', 'Pass — gap satisfies H/3'), ('FAIL', 'Fail — gap is less than required'), ('NA', 'N/A — single tower, no pair to check')], default='NA', max_length=10)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footprints', to='placement_engine.buildingplacement')),
            ],
            options={
                'ordering': ['placement', 'tower_index'],
            },
        ),
    ]
