# Generated by Django 4.2.28 on 2026-02-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footprintrecord',
            name='core_validation',
            field=models.JSONField(default=dict, help_text='CoreValidationResult dict: core_fit_status, selected_pattern, core_area_estimate_sqm, remaining_usable_sqm, lift_required, n_staircases_required, core_pkg_width_m, core_pkg_depth_m, audit_log.'),
        ),
        migrations.AlterField(
            model_name='buildingplacement',
            name='status',
            field=models.CharField(choices=[('VALID', 'Valid — all towers placed with spacing satisfied'), ('TOO_TIGHT', 'Too tight — fewer towers placed or spacing fail'), ('NO_FIT', 'No fit — not even one tower can fit'), ('NO_FIT_CORE', 'No core fit — footprint placed but building core cannot fit'), ('INVALID_INPUT', 'Invalid input — bad parameters'), ('ERROR', 'Unexpected error during computation')], max_length=20),
        ),
    ]
