# Generated by Django 4.2.28 on 2026-02-24 12:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('VALID', 'Valid — envelope computed successfully'), ('COLLAPSED', 'Collapsed — margins exceed plot dimensions'), ('TOO_SMALL', 'Too small — envelope below minimum buildable area'), ('INVALID_GEOM', 'Invalid geometry — plot polygon is degenerate'), ('INSUFFICIENT_INPUT', 'Insufficient input — road_facing_edges not declared'), ('ERROR', 'Unexpected error during computation')], max_length=30)),
                ('error_message', models.TextField(blank=True, help_text='Populated when status is COLLAPSED / INVALID_GEOM / ERROR.')),
                ('margin_geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Polygon after per-edge margin offsets only.', null=True, srid=0)),
                ('gc_geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Polygon after ground coverage enforcement.', null=True, srid=0)),
                ('envelope_geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Final buildable footprint (legal envelope).', null=True, srid=0)),
                ('common_plot_geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Carved 10% common open-space strip.', null=True, srid=0)),
                ('envelope_area_sqft', models.FloatField(blank=True, help_text='Area of the final buildable envelope in sq.ft.', null=True)),
                ('ground_coverage_pct', models.FloatField(blank=True, help_text='Ground coverage percentage: envelope_area / plot_area × 100.', null=True)),
                ('gc_status', models.CharField(choices=[('OK', 'Within GC limit'), ('CLIPPED', 'Clipped to satisfy GC limit'), ('MEASURE_ONLY', 'GDCR GC limit not yet defined — measured only'), ('NO_LIMIT', 'GC enforcement disabled'), ('NA', 'Not applicable')], default='NA', max_length=20)),
                ('common_plot_area_sqft', models.FloatField(blank=True, help_text='Area of the carved common plot in sq.ft.', null=True)),
                ('common_plot_status', models.CharField(choices=[('CARVED', 'Common plot carved from rear'), ('NO_CARVE_NEEDED', 'Rear margin zone satisfies 10% requirement'), ('NO_REAR_EDGE', 'No rear edge identified — carving skipped'), ('NA', 'Not applicable')], default='NA', max_length=20)),
                ('edge_margin_audit', models.JSONField(default=list, help_text='List of dicts, one per plot edge: {edge_index, edge_type, margin_m, margin_dxf, gdcr_clause, ...}')),
                ('road_facing_edges', models.JSONField(default=list, help_text='Edge indices declared as road-facing at computation time.')),
                ('building_height_used', models.FloatField(blank=True, help_text='Building height (m) used for margin table lookups.', null=True)),
                ('road_width_used', models.FloatField(blank=True, help_text='Road width (m) used for road-side margin lookup.', null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelopes', to='rules_engine.buildingproposal')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
    ]
