# Generated by Django 5.2.8 on 2026-03-01 10:12

from django.db import migrations, models


def set_tp14_fp126_road_from_plan(apps, schema_editor):
    """Set TP14 FP126 road width to 15 m per cadastral plan (15.00 MT)."""
    Plot = apps.get_model("tp_ingestion", "Plot")
    Plot.objects.filter(tp_scheme="TP14", fp_number="126").update(
        road_width_m=15.0,
        road_edges="0",
    )


def noop_reverse(apps, schema_editor):
    Plot = apps.get_model("tp_ingestion", "Plot")
    Plot.objects.filter(tp_scheme="TP14", fp_number="126").update(
        road_width_m=None,
        road_edges="",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tp_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='road_edges',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='plot',
            name='road_width_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunPython(set_tp14_fp126_road_from_plan, noop_reverse),
    ]
