# Generated by Django 4.2.28 on 2026-02-24 09:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('tp_scheme', models.CharField(max_length=100)),
                ('fp_number', models.CharField(max_length=50)),
                ('area_excel', models.FloatField()),
                ('area_geometry', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=0)),
                ('validation_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tp_scheme', 'fp_number'],
                'unique_together': {('city', 'tp_scheme', 'fp_number')},
            },
        ),
    ]
